name: ecosail
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  http: ^0.13.3
  cupertino_icons: ^1.0.2
  fl_chart: ^0.40.6
  sliding_sheet: ^0.5.2
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  flutter_map: ^0.14.0
  geocode: ^1.0.1
  tuple: ^2.0.0
  latlong2: ^0.8.1
  positioned_tap_detector_2: ^1.0.4
  transparent_image: ^2.0.0
  async: ^2.8.1
  flutter_image: ^4.1.0
  vector_math: ^2.1.0
  proj4dart: ^2.0.0
  meta: ^1.7.0
  collection: ^1.15.0
  intl: ^0.17.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  fluttertoast: ^8.0.8


flutter:

  uses-material-design: true

  assets:
    - images/
